package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer addressId;
     private Person person;
     private String postalAddress;
     private String telephone;
     private String addresscol;

    public Address() {
    }

	
    public Address(Person person) {
        this.person = person;
    }
    public Address(Person person, String postalAddress, String telephone, String addresscol) {
       this.person = person;
       this.postalAddress = postalAddress;
       this.telephone = telephone;
       this.addresscol = addresscol;
    }
   
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getPostalAddress() {
        return this.postalAddress;
    }
    
    public void setPostalAddress(String postalAddress) {
        this.postalAddress = postalAddress;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getAddresscol() {
        return this.addresscol;
    }
    
    public void setAddresscol(String addresscol) {
        this.addresscol = addresscol;
    }




}


