package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Events generated by hbm2java
 */
public class Events  implements java.io.Serializable {


     private Integer idevent;
     private String name;
     private String eventDatatype;
     private Boolean singletonEvent;
     private String minValue;
     private String maxValue;
     private String description;
     private Set personeventses = new HashSet(0);
     private Set eventValueses = new HashSet(0);
     private Set surveillances = new HashSet(0);

    public Events() {
    }

    public Events(String name, String eventDatatype, Boolean singletonEvent, String minValue, String maxValue, String description, Set personeventses, Set eventValueses, Set surveillances) {
       this.name = name;
       this.eventDatatype = eventDatatype;
       this.singletonEvent = singletonEvent;
       this.minValue = minValue;
       this.maxValue = maxValue;
       this.description = description;
       this.personeventses = personeventses;
       this.eventValueses = eventValueses;
       this.surveillances = surveillances;
    }
   
    public Integer getIdevent() {
        return this.idevent;
    }
    
    public void setIdevent(Integer idevent) {
        this.idevent = idevent;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEventDatatype() {
        return this.eventDatatype;
    }
    
    public void setEventDatatype(String eventDatatype) {
        this.eventDatatype = eventDatatype;
    }
    public Boolean getSingletonEvent() {
        return this.singletonEvent;
    }
    
    public void setSingletonEvent(Boolean singletonEvent) {
        this.singletonEvent = singletonEvent;
    }
    public String getMinValue() {
        return this.minValue;
    }
    
    public void setMinValue(String minValue) {
        this.minValue = minValue;
    }
    public String getMaxValue() {
        return this.maxValue;
    }
    
    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getPersoneventses() {
        return this.personeventses;
    }
    
    public void setPersoneventses(Set personeventses) {
        this.personeventses = personeventses;
    }
    public Set getEventValueses() {
        return this.eventValueses;
    }
    
    public void setEventValueses(Set eventValueses) {
        this.eventValueses = eventValueses;
    }
    public Set getSurveillances() {
        return this.surveillances;
    }
    
    public void setSurveillances(Set surveillances) {
        this.surveillances = surveillances;
    }




}


