package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Facility generated by hbm2java
 */
public class Facility  implements java.io.Serializable {


     private int mflcode;
     private Location location;
     private String facilityname;
     private Set personeventses = new HashSet(0);

    public Facility() {
    }

	
    public Facility(int mflcode, Location location) {
        this.mflcode = mflcode;
        this.location = location;
    }
    public Facility(int mflcode, Location location, String facilityname, Set personeventses) {
       this.mflcode = mflcode;
       this.location = location;
       this.facilityname = facilityname;
       this.personeventses = personeventses;
    }
   
    public int getMflcode() {
        return this.mflcode;
    }
    
    public void setMflcode(int mflcode) {
        this.mflcode = mflcode;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getFacilityname() {
        return this.facilityname;
    }
    
    public void setFacilityname(String facilityname) {
        this.facilityname = facilityname;
    }
    public Set getPersoneventses() {
        return this.personeventses;
    }
    
    public void setPersoneventses(Set personeventses) {
        this.personeventses = personeventses;
    }




}


