package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * IdentifierType generated by hbm2java
 */
public class IdentifierType  implements java.io.Serializable {
    
    public enum IdentifierTypeName{
        CCC_NUMBER,
        ANC_NUMBER,
        PMTCT_NUMBER
    }


     private Integer identifierTypeId;
     private String identifierTypeName;
     private Set personIdentifiers = new HashSet(0);

    public IdentifierType() {
    }

    public IdentifierType(String identifierTypeName, Set personIdentifiers) {
       this.identifierTypeName = identifierTypeName;
       this.personIdentifiers = personIdentifiers;
    }
   
    public Integer getIdentifierTypeId() {
        return this.identifierTypeId;
    }
    
    public void setIdentifierTypeId(Integer identifierTypeId) {
        this.identifierTypeId = identifierTypeId;
    }
    public String getIdentifierTypeName() {
        return this.identifierTypeName;
    }
    
    public void setIdentifierTypeName(String identifierTypeName) {
        this.identifierTypeName = identifierTypeName;
    }
    public Set getPersonIdentifiers() {
        return this.personIdentifiers;
    }
    
    public void setPersonIdentifiers(Set personIdentifiers) {
        this.personIdentifiers = personIdentifiers;
    }




}


