package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int locationId;
     private String villageName;
     private String county;
     private String subcounty;
     private String district;
     private String location;
     private String subLocation;
     private String landmark;
     private Set persons = new HashSet(0);
     private Set facilities = new HashSet(0);

    public Location() {
    }

	
    public Location(int locationId) {
        this.locationId = locationId;
    }
    public Location(int locationId, String villageName, String county, String subcounty, String district, String location, String subLocation, String landmark, Set persons, Set facilities) {
       this.locationId = locationId;
       this.villageName = villageName;
       this.county = county;
       this.subcounty = subcounty;
       this.district = district;
       this.location = location;
       this.subLocation = subLocation;
       this.landmark = landmark;
       this.persons = persons;
       this.facilities = facilities;
    }
   
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }
    public String getVillageName() {
        return this.villageName;
    }
    
    public void setVillageName(String villageName) {
        this.villageName = villageName;
    }
    public String getCounty() {
        return this.county;
    }
    
    public void setCounty(String county) {
        this.county = county;
    }
    public String getSubcounty() {
        return this.subcounty;
    }
    
    public void setSubcounty(String subcounty) {
        this.subcounty = subcounty;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getSubLocation() {
        return this.subLocation;
    }
    
    public void setSubLocation(String subLocation) {
        this.subLocation = subLocation;
    }
    public String getLandmark() {
        return this.landmark;
    }
    
    public void setLandmark(String landmark) {
        this.landmark = landmark;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }
    public Set getFacilities() {
        return this.facilities;
    }
    
    public void setFacilities(Set facilities) {
        this.facilities = facilities;
    }




}


