package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.kemricdc.constants.MaritalStatusTypeName;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer personId;
     private MaritalStatusTypeName maritalStatusType;
     private PatientSource patientSource;
     private Location location;
     private String personGuid;
     private String firstName;
     private String middleName;
     private String lastName;
     private String sex;
     private Date birthdate;
     private Date deathdate;
     private Date dateCreated;
     private Date dateModified;
     private Set personeventses = new HashSet(0);
     private Set relationshipsForPersonbId = new HashSet(0);
     private Set personIdentifiers = new HashSet(0);
     private Set relationshipsForPersonaId = new HashSet(0);
     private Set addresses = new HashSet(0);

    public Person() {
    }

	
    public Person(MaritalStatusTypeName maritalStatusType, PatientSource patientSource) {
        this.maritalStatusType = maritalStatusType;
        this.patientSource = patientSource;
    }
    public Person(MaritalStatusTypeName maritalStatusType, PatientSource patientSource, Location location, String personGuid, String firstName, String middleName, String lastName, String sex, Date birthdate, Date deathdate, Date dateCreated, Date dateModified, Set personeventses, Set relationshipsForPersonbId, Set personIdentifiers, Set relationshipsForPersonaId, Set addresses) {
       this.maritalStatusType = maritalStatusType;
       this.patientSource = patientSource;
       this.location = location;
       this.personGuid = personGuid;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.sex = sex;
       this.birthdate = birthdate;
       this.deathdate = deathdate;
       this.dateCreated = dateCreated;
       this.dateModified = dateModified;
       this.personeventses = personeventses;
       this.relationshipsForPersonbId = relationshipsForPersonbId;
       this.personIdentifiers = personIdentifiers;
       this.relationshipsForPersonaId = relationshipsForPersonaId;
       this.addresses = addresses;
    }
   
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
    public MaritalStatusTypeName getMaritalStatusType() {
        return this.maritalStatusType;
    }
    
    public void setMaritalStatusType(MaritalStatusTypeName maritalStatusType) {
        this.maritalStatusType = maritalStatusType;
    }
    public PatientSource getPatientSource() {
        return this.patientSource;
    }
    
    public void setPatientSource(PatientSource patientSource) {
        this.patientSource = patientSource;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getPersonGuid() {
        return this.personGuid;
    }
    
    public void setPersonGuid(String personGuid) {
        this.personGuid = personGuid;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public Date getDeathdate() {
        return this.deathdate;
    }
    
    public void setDeathdate(Date deathdate) {
        this.deathdate = deathdate;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Date getDateModified() {
        return this.dateModified;
    }
    
    public void setDateModified(Date dateModified) {
        this.dateModified = dateModified;
    }
    public Set getPersoneventses() {
        return this.personeventses;
    }
    
    public void setPersoneventses(Set personeventses) {
        this.personeventses = personeventses;
    }
    public Set getRelationshipsForPersonbId() {
        return this.relationshipsForPersonbId;
    }
    
    public void setRelationshipsForPersonbId(Set relationshipsForPersonbId) {
        this.relationshipsForPersonbId = relationshipsForPersonbId;
    }
    public Set getPersonIdentifiers() {
        return this.personIdentifiers;
    }
    
    public void setPersonIdentifiers(Set personIdentifiers) {
        this.personIdentifiers = personIdentifiers;
    }
    public Set getRelationshipsForPersonaId() {
        return this.relationshipsForPersonaId;
    }
    
    public void setRelationshipsForPersonaId(Set relationshipsForPersonaId) {
        this.relationshipsForPersonaId = relationshipsForPersonaId;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }

    @Override
    public String toString() {
        return "Person{" + "personId=" + personId + ", maritalStatusType=" + maritalStatusType + ", patientSource=" + patientSource + ", location=" + location + ", personGuid=" + personGuid + ", firstName=" + firstName + ", middleName=" + middleName + ", lastName=" + lastName + ", sex=" + sex + ", birthdate=" + birthdate + ", deathdate=" + deathdate + ", dateCreated=" + dateCreated + ", dateModified=" + dateModified + ", personeventses=" + personeventses + ", relationshipsForPersonbId=" + relationshipsForPersonbId + ", personIdentifiers=" + personIdentifiers + ", relationshipsForPersonaId=" + relationshipsForPersonaId + ", addresses=" + addresses + '}';
    }

    



}


