package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0

import org.kemricdc.constants.IdentifierTypeName;




/**
 * PersonIdentifier generated by hbm2java
 */
public class PersonIdentifier  implements java.io.Serializable {


     private Integer personIdentifierId;
     private IdentifierTypeName identifierType;
     private Person person;
     private String identifier;

    public PersonIdentifier() {
    }

	
    public PersonIdentifier(IdentifierTypeName identifierType, Person person) {
        this.identifierType = identifierType;
        this.person = person;
    }
    public PersonIdentifier(IdentifierTypeName identifierType, Person person, String identifier) {
       this.identifierType = identifierType;
       this.person = person;
       this.identifier = identifier;
    }
   
    public Integer getPersonIdentifierId() {
        return this.personIdentifierId;
    }
    
    public void setPersonIdentifierId(Integer personIdentifierId) {
        this.personIdentifierId = personIdentifierId;
    }
    public IdentifierTypeName getIdentifierType() {
        return this.identifierType;
    }
    
    public void setIdentifierType(IdentifierTypeName identifierType) {
        this.identifierType = identifierType;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getIdentifier() {
        return this.identifier;
    }
    
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }




}


