package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0



/**
 * Relationship generated by hbm2java
 */
public class Relationship  implements java.io.Serializable {


     private RelationshipId id;
     private Person personByPersonaId;
     private Person personByPersonbId;
     private RelationshipType relationshipType;

    public Relationship() {
    }

    public Relationship(RelationshipId id, Person personByPersonaId, Person personByPersonbId, RelationshipType relationshipType) {
       this.id = id;
       this.personByPersonaId = personByPersonaId;
       this.personByPersonbId = personByPersonbId;
       this.relationshipType = relationshipType;
    }
   
    public RelationshipId getId() {
        return this.id;
    }
    
    public void setId(RelationshipId id) {
        this.id = id;
    }
    public Person getPersonByPersonaId() {
        return this.personByPersonaId;
    }
    
    public void setPersonByPersonaId(Person personByPersonaId) {
        this.personByPersonaId = personByPersonaId;
    }
    public Person getPersonByPersonbId() {
        return this.personByPersonbId;
    }
    
    public void setPersonByPersonbId(Person personByPersonbId) {
        this.personByPersonbId = personByPersonbId;
    }
    public RelationshipType getRelationshipType() {
        return this.relationshipType;
    }
    
    public void setRelationshipType(RelationshipType relationshipType) {
        this.relationshipType = relationshipType;
    }




}


