package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * RelationshipType generated by hbm2java
 */
public class RelationshipType  implements java.io.Serializable {


     private int relationshipTypeId;
     private String relationshipType;
     private Set relationships = new HashSet(0);

    public RelationshipType() {
    }

	
    public RelationshipType(int relationshipTypeId) {
        this.relationshipTypeId = relationshipTypeId;
    }
    public RelationshipType(int relationshipTypeId, String relationshipType, Set relationships) {
       this.relationshipTypeId = relationshipTypeId;
       this.relationshipType = relationshipType;
       this.relationships = relationships;
    }
   
    public int getRelationshipTypeId() {
        return this.relationshipTypeId;
    }
    
    public void setRelationshipTypeId(int relationshipTypeId) {
        this.relationshipTypeId = relationshipTypeId;
    }
    public String getRelationshipType() {
        return this.relationshipType;
    }
    
    public void setRelationshipType(String relationshipType) {
        this.relationshipType = relationshipType;
    }
    public Set getRelationships() {
        return this.relationships;
    }
    
    public void setRelationships(Set relationships) {
        this.relationships = relationships;
    }




}


