package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0



/**
 * RelationshipId generated by hbm2java
 */
public class RelationshipId  implements java.io.Serializable {


     private int personaId;
     private int personbId;
     private int relationshipTypeId;

    public RelationshipId() {
    }

    public RelationshipId(int personaId, int personbId, int relationshipTypeId) {
       this.personaId = personaId;
       this.personbId = personbId;
       this.relationshipTypeId = relationshipTypeId;
    }
   
    public int getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(int personaId) {
        this.personaId = personaId;
    }
    public int getPersonbId() {
        return this.personbId;
    }
    
    public void setPersonbId(int personbId) {
        this.personbId = personbId;
    }
    public int getRelationshipTypeId() {
        return this.relationshipTypeId;
    }
    
    public void setRelationshipTypeId(int relationshipTypeId) {
        this.relationshipTypeId = relationshipTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelationshipId) ) return false;
		 RelationshipId castOther = ( RelationshipId ) other; 
         
		 return (this.getPersonaId()==castOther.getPersonaId())
 && (this.getPersonbId()==castOther.getPersonbId())
 && (this.getRelationshipTypeId()==castOther.getRelationshipTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPersonaId();
         result = 37 * result + this.getPersonbId();
         result = 37 * result + this.getRelationshipTypeId();
         return result;
   }   


}


