package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String name;
     private String password;
     private Set personeventses = new HashSet(0);

    public User() {
    }

    public User(String name, String password, Set personeventses) {
       this.name = name;
       this.password = password;
       this.personeventses = personeventses;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getPersoneventses() {
        return this.personeventses;
    }
    
    public void setPersoneventses(Set personeventses) {
        this.personeventses = personeventses;
    }




}


